# Generated by Django 5.0.1 on 2024-03-20 20:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='goalsdreams',
            name='achieved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='goalsdreams',
            name='date_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='goalsdreams',
            name='hours_required',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='goalsdreams',
            name='hours_spent',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
